### ISSUE TITLE
SpeechToText Index out of bounds

### ISSUE THREAD

**Issue by Nailik** [Nailik/rhasspy_mobile#236]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=1280 srcPos=0 dst.length=9600 dstPos=8960 length=1280
       at java.lang.System.arraycopy(System.java)
       at java.util.ArrayList.addAll(ArrayList.java:591)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService.audioFrame(SpeechToTextService.kt:129)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService.access$audioFrame(SpeechToTextService.kt:26)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService$startSpeechToText$3$1.emit(SpeechToTextService.kt:111)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService$startSpeechToText$3$1.emit(SpeechToTextService.kt:110)
       at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
       at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Nailik** [comment]
will be fixed with #217
