### ISSUE TITLE
Koin no bean definition found

### ISSUE THREAD

**Issue by Nailik** [Nailik/rhasspy_mobile#276]
Instead of reloading Koin only reload the services where necessary when saving or testing. This should fix that the definition is missing.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.rhasspy.mobile.android/org.rhasspy.mobile.android.MainActivity}: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'org.rhasspy.mobile.viewmodel.screens.HomeScreenViewModel' q:''. Check your definitions!
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5307)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5215)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

```
Caused by org.koin.core.error.NoBeanDefFoundException: No definition found for class:'org.rhasspy.mobile.viewmodel.screens.HomeScreenViewModel' q:''. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:298)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:268)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.java:133)
       at org.rhasspy.mobile.android.MainActivity.onCreate(MainActivity.kt:77)
       at android.app.Activity.performCreate(Activity.java:7802)
       at android.app.Activity.performCreate(Activity.java:7791)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5307)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5215)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

```
Fatal Exception: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'org.rhasspy.mobile.middleware.ServiceMiddleware' q:''. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:298)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:268)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at org.koin.core.scope.Scope.get$default(Scope.java:133)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService$special$$inlined$inject$default$5.invoke(KoinComponent.kt:61)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService.getServiceMiddleware(SpeechToTextService.kt:42)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService.endSpeechToText(SpeechToTextService.kt:90)
       at org.rhasspy.mobile.services.speechtotext.SpeechToTextService$endSpeechToText$1.invokeSuspend(SpeechToTextService.kt:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Nailik** [comment]
will be fixed with #299
