### ISSUE TITLE
NoClassDef java/nio/file/Paths

### ISSUE THREAD

**Issue by Nailik** [Nailik/rhasspy_mobile#492]
Caused by java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/org.rhasspy.mobile.android-1/base.apk", zip file "/data/app/org.rhasspy.mobile.android-1/split_config.arm64_v8a.apk", zip file "/data/app/org.rhasspy.mobile.android-1/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/org.rhasspy.mobile.android-1/lib/arm64, /data/app/org.rhasspy.mobile.android-1/base.apk!/lib/arm64-v8a, /data/app/org.rhasspy.mobile.android-1/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/org.rhasspy.mobile.android-1/split_config.xhdpi.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at okio.Path.toNioPath(Path.java:48)
       at org.rhasspy.mobile.platformspecific.extensions.PathExtensionsKt.commonSource(PathExtensions.kt:48)
       at org.rhasspy.mobile.logic.services.mqtt.MqttService.audioCaptured(MqttService.java:48)
       at org.rhasspy.mobile.logic.services.dialog.states.StateTransition.transitionToTranscribingIntentState(StateTransition.kt:48)
       at org.rhasspy.mobile.logic.services.dialog.dialogmanager.mqtt.DialogManagerMqtt.onStopListening(DialogManagerMqtt.java:71)
       at org.rhasspy.mobile.logic.services.dialog.dialogmanager.mqtt.DialogManagerMqtt.onAction(DialogManagerMqtt.java:71)
       at org.rhasspy.mobile.logic.services.dialog.DialogManagerService.onAction(DialogManagerService.kt:71)
       at org.rhasspy.mobile.logic.middleware.ServiceMiddleware$action$1.invokeSuspend(ServiceMiddleware.kt:965)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)

**Comment by Nailik** [comment]
closed b https://github.com/Nailik/rhasspy_mobile/pull/493
